### ISSUE TITLE
Corp proxy does ssl cert intercept and returns self signed cert that fails because there is no option to set verify to false

### ISSUE THREAD

**Issue by JoeyG1973** [simoncadman/CUPS-Cloud-Print#113]
Please add an option to set verify=false on ssl

http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

**Comment by virtualdll** [comment]
requests.packages.urllib3.disable_warnings()

**Comment by JoeyG1973** [comment]
That would certainly prevent it from showing the warning but that is not the issue.  I am getting this.

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

**Comment by virtualdll** [comment]
PYTHONHTTPSVERIFY=0

**Comment by JoeyG1973** [comment]
nope

```root@ubuntu:~# export PYTHONHTTPSVERIFY=0
root@ubuntu:~# /usr/share/cloudprint-cups/setupcloudprint.py 
Traceback (most recent call last):
  File "/usr/share/cloudprint-cups/setupcloudprint.py", line 95, in <module>
    requestors, storage = Auth.SetupAuth(True)
  File "/usr/share/cloudprint-cups/auth.py", line 189, in SetupAuth
    Auth.RenewToken(interactive, requestor, credentials, storage, userid)
  File "/usr/share/cloudprint-cups/auth.py", line 46, in RenewToken
    credentials.refresh(requestor)
  File "/usr/share/cloudprint-cups/oauth2client/client.py", line 633, in refresh
    self._refresh(http.request)
  File "/usr/share/cloudprint-cups/oauth2client/client.py", line 854, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/share/cloudprint-cups/oauth2client/client.py", line 874, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by virtualdll** [comment]
It seems like they are decrypting your traffic inline. Have you tried installing the certificate authority onto the system so it sees the cert they give back to you as valid?

**Comment by JoeyG1973** [comment]
That is exactly what they are doing.  Unfortunately the did this without knowing what they are doing.  All 4 certs are installed and I know they are working because I can run a curl to google on https and I do not get an issue with the certs.  I am running on Ubuntu 16.04.

**Comment by JoeyG1973** [comment]
I actually think the issue is with python package certifi in /usr/local/lib/python2.7/dist-packages/certifi

There is a big old cacert.pem that i think is where python 2.7 is getting all it's CAs from and not from the system.  Unfortunately I cannot uninstall it because so much relies on it.

**Comment by virtualdll** [comment]
Sorry for the quick answers haven't had time to stop. doing this from phone. 
does this help?
http://stackoverflow.com/questions/32761774/requests-ssl-certificate-verify-failed-with-verify-cabundle-crt

If not could you provide OpenSSL version, python version, version of libraries, and OS you are using. 

Since curl is working without issue or additional flags, I'm thinking the cert setup is ok.  You may need to specify the cert explicitly for python or you may be running into a bug with current versions that you are using.

**Comment by JoeyG1973** [comment]
I tried to add the cert to the cacerts.pem file in certifi module.  Just for good measure installed requests modules and added it there.  No luck.

Also PIP suffers from the same issue, but the way I get around it is to use this:

```
pip install --index-url=http://pypi.python.org/simple --trusted-host pypi.python.org <packagename>
```

The weird thing is that I tried the test script I found here:

```
https://access.redhat.com/articles/2039753#troubleshooting-certificate-verification-8
```

And I point it to https://google.com ( my corporate overlords do not allow us to connect to https://cdn.redhat.com ) and that works just fine

```
root@ubuntu:~# python urllib2-test.py https://google.com
```

It returns nothing so it is working.

Here are the versions:

```
root@ubuntu:~# openssl version -a
OpenSSL 1.0.2g  1 Mar 2016
built on: reproducible build, date unspecified
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: cc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/lib/ssl"

root@ubuntu:~# python --version
Python 2.7.12

root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

root@ubuntu:~# pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
anoise (0.0.25)
anoise-media (0.0.17)
ansible (2.1.0.0)
apsw (3.8.11.1.post1)
attrs (15.2.0)
awscli (1.11.24)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.4.1)
blinker (1.3)
botocore (1.4.81)
CDApplet (1.0)
CDBashApplet (1.0)
certifi (2015.4.28)
cffi (1.6.0)
characteristic (14.3.0)
chardet (2.3.0)
CherryPy (3.5.0)
colorama (0.3.7)
command-not-found (0.3)
cryptography (1.4)
cssselect (0.9.1)
cssutils (1.0)
debtags (2.0)
defer (1.0.6)
dirspec (13.10)
dnspython (1.12.0)
docutils (0.12)
duplicity (0.7.6)
ecdsa (0.13)
enum34 (1.1.6)
feedparser (5.1.3)
futures (3.0.5)
Genshi (0.7)
google-api-python-client (1.5.1)
html5lib (0.999)
httplib2 (0.9.2)
idna (2.1)
ipaddress (1.0.16)
Jinja2 (2.8)
jmespath (0.9.0)
lockfile (0.12.2)
lxml (3.5.0)
Markdown (2.6.6)
MarkupSafe (0.23)
mechanize (0.2.5)
meld (3.14.2)
ndg-httpsclient (0.4.0)
netaddr (0.7.18)
netifaces (0.10.4)
oauth2client (2.1.0)
oauthlib (1.0.3)
oneconf (0.3.9)
PAM (0.4.2)
paramiko (2.0.0)
Pillow (3.1.2)
pip (9.0.1)
piston-mini-client (0.7.5)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.73)
Pygments (2.1)
pygobject (3.20.0)
PyJWT (1.3.0)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyserial (3.0.1)
pysqlite (2.7.0)
python-apt (1.1.0b1)
python-cloudfiles (1.7.10)
python-dateutil (2.4.2)
python-debian (0.1.27)
pyxdg (0.25)
PyYAML (3.11)
repoze.lru (0.6)
Routes (2.2)
rsa (3.4.2)
s3transfer (0.1.9)
service-identity (16.0.0)
setuptools (23.0.0)
simplejson (3.8.2)
six (1.10.0)
software-center-aptd-plugins (0.0.0)
Trac (1.2)
Twisted (16.0.0)
uritemplate (0.6)
urllib3 (1.13.1)
uTidylib (0.2)
WebOb (1.5.1)
wheel (0.29.0)
zenmap (7.1)
zope.interface (4.1.3)
```

**Comment by mblyeks** [comment]
Hi, were you ever able to solve this problem?  I have the exact same one.
