### ISSUE TITLE
setupcloudprint.py error on Yosemite

### ISSUE THREAD

**Issue by bentljo** [simoncadman/CUPS-Cloud-Print#85]
When I run the setupcloudprint.py script I get:
ImportError: No module named cups

What am I doing wrong?

**Comment by simoncadman** [comment]
Hi bentljo,

Are you using the Mac package ( https://niftyrepo.niftiestsoftware.com/cups-cloud-print/packages/cupscloudprint-20140814.3.pkg ) to install? In my testing it works fine on a fresh install of Yosemite.

Simon

**Comment by bentljo** [comment]
Yes, that is the version I used. I have only used it on my MacBook but I
will try a different one also with Yosemite. I had wondered if possibly my
current configuration might have something to do with it.

**Comment by bentljo** [comment]
Same error on the 2nd Yosemite install.  But these are configured
similarly.

**Comment by candrews** [comment]
This seems similar to #87 - the package needs to depend on python-cups but does not. If you install the package manually, the problem will be resolved.

**Comment by simoncadman** [comment]
The Mac package is supposed to install pycups ( see https://github.com/simoncadman/CUPS-Cloud-Print/blob/master/packages/darwin/preinstall#L11 ) but I guess it's possible it's not always working. 

If someone still experiencing the problem on OS X can try:


export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments
sudo -E /usr/bin/easy_install pycups

It would be useful to see what the output is.

Thanks

**Comment by saitooo** [comment]
I've ran into the same problem on 10.11.6 (`/usr/bin/sw_vers -productVersion`).

Turns out you'll need XCode installed.

`sudo /usr/bin/easy_install pycups` breaks with:
```
Searching for pycups
Reading https://pypi.python.org/simple/pycups/
Best match: pycups 1.9.73
Downloading https://pypi.python.org/packages/7c/ea/7a9bf1e69e001bdd6ee2909f08d44d9fcb9d196933236eaa99fa3b155749/pycups-1.9.73.tar.bz2#md5=ee0e7204d7a2ae942e2f4c4508afdbfb
Processing pycups-1.9.73.tar.bz2
Writing /var/folders/sb/_l7_wc9d7sq051cz7fxvxyq15d_cxb/T/easy_install-Hldd8K/pycups-1.9.73/setup.cfg
Running pycups-1.9.73/setup.py -q bdist_egg --dist-dir /var/folders/sb/_l7_wc9d7sq051cz7fxvxyq15d_cxb/T/easy_install-Hldd8K/pycups-1.9.73/egg-dist-tmp-v2HZGI
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
error: Setup script exited with error: command 'cc' failed with exit status 1
```

**Comment by saitooo** [comment]
Even with Xcode command line tools installed, it won't work.

`pycups` installation throws a lot of warnings (I've exported the flags from the package). It still says
```
Adding pycups 1.9.73 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/pycups-1.9.73-py2.7-macosx-10.11-intel.egg
Processing dependencies for pycups
Finished processing dependencies for pycups
```
though. I'm no Python expert but I'd say that it's installed successfully.

When I try to launch the `setupcloudprint.py` script, I'm stopped at
```./setupcloudprint.py 
Traceback (most recent call last):
  File "./setupcloudprint.py", line 63, in <module>
    import cups
  File "build/bdist.macosx-10.11-intel/egg/cups.py", line 7, in <module>
  File "build/bdist.macosx-10.11-intel/egg/cups.py", line 4, in __bootstrap__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 884, in resource_filename
    self, resource_name
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1523, in get_resource_filename
    self._extract_resource(manager, self._eager_to_zip(name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1551, in _extract_resource
    self.egg_name, self._parts(zip_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 950, in get_cache_path
    self.extraction_error()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 930, in extraction_error
    raise err
pkg_resources.ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 13] Permission denied: '/var/empty/.python-eggs'

The Python egg cache directory is currently set to:

  /var/empty/.python-eggs

Perhaps your account does not have write access to this directory?  You can
change the cache directory by setting the PYTHON_EGG_CACHE environment
variable to point to an accessible directory.
```

Any ideas?

**Comment by virtualdll** [comment]
I would say try running as sudo and/or check permissions. Another option would be to set the cache directory to a folder you know exists and you have access to. 

export PYTHON_EGG_CACHE="~/mycachefolder"

Thanks,
David Lamb
